# Generated by Django 5.1.2 on 2024-10-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpilot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
