# Generated by Django 5.1.2 on 2024-10-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskpilot_app', '0002_remove_projects_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='start_date',
        ),
    ]
