# Generated by Django 5.1.2 on 2024-10-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskpilot_app', '0003_alter_comments_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='password',
        ),
    ]
