# Generated by Django 5.1.2 on 2024-10-18 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpilot_app', '0004_alter_comments_author_alter_projects_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskpilot_app.workers'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskpilot_app.clients'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskpilot_app.workers'),
        ),
    ]
