# Generated by Django 5.1.2 on 2024-10-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpilot_app', '0005_alter_tasks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='task_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskpilot_app.projects'),
            preserve_default=False,
        ),
    ]
